# Generated by Django 5.1.7 on 2025-03-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantimage',
            options={'verbose_name': ('Рисунок растения',), 'verbose_name_plural': 'Рисунки растений'},
        ),
        migrations.AddField(
            model_name='plant',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
