# Generated by Django 5.1.7 on 2025-03-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_plantimage_options_plant_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Скидка'),
        ),
    ]
