# Generated by Django 5.1.7 on 2025-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_plantcomment_delete_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='plantimage',
            options={'verbose_name': 'Рисунок растения', 'verbose_name_plural': 'Рисунки растений'},
        ),
        migrations.AlterField(
            model_name='plant',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
    ]
